name: Node CI

on: [push]

jobs:
  build:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '16'
          cache: 'yarn'

      - name: yarn install
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: yarn test:coverage
        if: github.ref == 'refs/heads/master'
        run: yarn test:coverage
        env:
          CI: true

      - name: Upload Coverage to codecov
        if: github.ref == 'refs/heads/master'
        uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./packages/server/coverage/clover.xml

      - name: yarn test
        if: github.ref != 'refs/heads/master'
        run: yarn test
        env:
          CI: true
